name: sec-analyzer
channels:
  - defaults
dependencies:
  - python=3.10.9
  - pip=22.3.1
  - pip:
    - aiohttp==3.8.4
    - aiosignal==1.3.1
    - async-timeout==4.0.2
    - attrs==22.2.0
    - beautifulsoup4==4.11.2
    - boto3==1.26.114
    - botocore==1.29.114
    - bpemb==0.3.4
    - bs4==0.0.1
    - certifi==2022.12.7
    - charset-normalizer==3.0.1
    - click==8.1.3
    - cloudpickle==2.2.1
    - conllu==4.5.2
    - contourpy==1.0.7
    - cssutils==2.6.0
    - cycler==0.11.0
    - datasets==2.11.0
    - Deprecated==1.2.13
    - dill==0.3.6
    - emoji==2.2.0
    - Faker==17.0.0
    - filelock==3.9.0
    - flair==0.12.2
    - Flask==2.2.3
    - Flask-Cors==3.0.10
    - fonttools==4.38.0
    - frozenlist==1.3.3
    - fsspec==2023.4.0
    - ftfy==6.1.1
    - future==0.18.3
    - gdown==4.4.0
    - gensim==4.3.1
    - huggingface-hub==0.12.1
    - hyperopt==0.2.7
    - idna==3.4
    - itsdangerous==2.1.2
    - Janome==0.4.2
    - Jinja2==3.1.2
    - jmespath==1.0.1
    - joblib==1.2.0
    - kaleido==0.2.1
    - kiwisolver==1.4.4
    - langdetect==1.0.9
    - lxml==4.9.2
    - MarkupSafe==2.1.2
    - matplotlib==3.7.0
    - more-itertools==9.1.0
    - mpld3==0.3
    - multidict==6.0.4
    - multiprocess==0.70.14
    - networkx==3.1
    - nltk==3.8.1
    - numpy==1.24.2
    - packaging==23.0
    - pandas==1.5.3
    - Pillow==9.4.0
    - plotly==5.13.0
    - pptree==3.1
    - protobuf==3.20.2
    - py4j==0.10.9.7
    - pyarrow==11.0.0
    - pyparsing==3.0.9
    - PySocks==1.7.1
    - python-dateutil==2.8.2
    - pytorch_revgrad==0.2.0
    - pytz==2022.7.1
    - PyYAML==6.0
    - regex==2022.10.31
    - requests==2.28.2
    - responses==0.18.0
    - s3transfer==0.6.0
    - scikit-learn==1.2.2
    - scipy==1.10.1
    - sec-edgar-downloader==4.3.0
    - segtok==1.5.11
    - sentencepiece==0.1.98
    - six==1.16.0
    - smart-open==6.3.0
    - soupsieve==2.4
    - sqlitedict==2.1.0
    - stanza==1.4.2
    - tabulate==0.9.0
    - tenacity==8.2.1
    - threadpoolctl==3.1.0
    - tokenizers==0.13.2
    - torch==1.13.1
    - tqdm==4.64.1
    - transformer-smaller-training-vocab==0.2.3
    - transformers==4.26.1
    - typing_extensions==4.5.0
    - urllib3==1.26.14
    - wcwidth==0.2.6
    - Werkzeug==2.2.3
    - Wikipedia-API==0.5.8
    - wordcloud==1.8.2.2
    - wrapt==1.15.0
    - xxhash==3.2.0
    - yarl==1.8.2

