name: sec-analyzer
channels:
  - defaults
dependencies:
  - python=3.10.9
  - pip=22.3.1
  - pip:
    - beautifulsoup4==4.11.2
    - bs4==0.0.1
    - certifi==2022.12.7
    - charset-normalizer==3.0.1
    - click==8.1.3
    - contourpy==1.0.7
    - cssutils==2.6.0
    - cycler==0.11.0
    - emoji==2.2.0
    - Faker==17.0.0
    - filelock==3.9.0
    - Flask==2.2.3
    - Flask-Cors==3.0.10
    - fonttools==4.38.0
    - huggingface-hub==0.12.1
    - idna==3.4
    - itsdangerous==2.1.2
    - Jinja2==3.1.2
    - joblib==1.2.0
    - kiwisolver==1.4.4
    - lxml==4.9.2
    - MarkupSafe==2.1.2
    - matplotlib==3.7.0
    - nltk==3.8.1
    - numpy==1.24.2
    - packaging==23.0
    - pandas==1.5.3
    - Pillow==9.4.0
    - plotly==5.13.0
    - protobuf==4.22.0
    - pyparsing==3.0.9
    - python-dateutil==2.8.2
    - pytz==2022.7.1
    - PyYAML==6.0
    - regex==2022.10.31
    - requests==2.28.2
    - sec-edgar-downloader==4.3.0
    - six==1.16.0
    - soupsieve==2.4
    - stanza==1.4.2
    - tenacity==8.2.1
    - tokenizers==0.13.2
    - torch==1.13.1
    - tqdm==4.64.1
    - transformers==4.26.1
    - typing_extensions==4.5.0
    - urllib3==1.26.14
    - Werkzeug==2.2.3
    - wordcloud==1.8.2.2
